### ISSUE TITLE
Support setting working directory for use with `pull_request_target` and subdirectory checkouts

### ISSUE THREAD

**Issue by YutaUra** [int128/update-generated-files-action#864]
Hey, thanks for the great action!

I understand that this action works well within the typical usage of GitHub Actions.  
However, I’ve found that it doesn't work as expected when the repository is checked out into a subdirectory—especially in workflows triggered by `pull_request_target`.

Here is an example where it doesn’t behave correctly:

```yaml
on:
  pull_request_target:
    branches: [ main ]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
        with:
          path: pull_request_target
          ref: ${{ github.event.pull_request.head.sha }}

      - run: pnpm install && pnpm run lint:fix
        working_directory: pull_request_target

      - uses: int128/update-generated-files-action@v2
        with:
          working_directory: pull_request_target # <- This does not work
```

In OSS projects, it's common to use `pull_request_target` to run CI for contributor PRs that require access to secrets.
To ensure security, workflows triggered by pull_request_target run on the default branch, so we must check out the PR code into a subdirectory and run tests or linters from there.

However, this action currently does not support specifying the working directory, which makes it unusable in such setups.

Would it be possible to add an option to set the working directory so the action can run correctly in these scenarios?
